import React from "react";
import { ScrollView, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { useColors } from "@/hooks/useColors";

function Section({ title, children }: { title: string; children: string }) {
  const C = useColors();
  return (
    <View style={{ marginBottom: 24 }}>
      <Text style={{ color: C.foreground, fontSize: 16, fontWeight: "700", marginBottom: 8 }}>
        {title}
      </Text>
      <Text style={{ color: C.mutedForeground, fontSize: 14, lineHeight: 22 }}>
        {children}
      </Text>
    </View>
  );
}

export default function TermsScreen() {
  const C = useColors();
  const insets = useSafeAreaInsets();
  const router = useRouter();

  return (
    <View style={{ flex: 1, backgroundColor: C.background }}>
      <View
        style={{
          paddingTop: insets.top + 12,
          paddingHorizontal: 20,
          paddingBottom: 16,
          flexDirection: "row",
          alignItems: "center",
          gap: 14,
          borderBottomWidth: 1,
          borderBottomColor: C.border,
        }}
      >
        <TouchableOpacity
          onPress={() => router.back()}
          style={{
            width: 38,
            height: 38,
            borderRadius: 12,
            backgroundColor: C.backgroundSecondary,
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Ionicons name="chevron-back" size={18} color={C.foreground} />
        </TouchableOpacity>
        <Text style={{ color: C.foreground, fontSize: 22, fontWeight: "800" }}>
          Terms of Service
        </Text>
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{
          paddingHorizontal: 20,
          paddingTop: 24,
          paddingBottom: insets.bottom + 40,
        }}
      >
        <Text style={{ color: C.mutedForeground, fontSize: 12, marginBottom: 24 }}>
          Last updated: May 2026
        </Text>

        <Section title="1. Acceptance of Terms">
          By downloading, installing, or using Liquid Impact ("the App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App.
        </Section>

        <Section title="2. Description of Service">
          Liquid Impact provides AI-powered drink analysis to help users understand the health impact of beverages they consume. The analysis is provided for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment.
        </Section>

        <Section title="3. User Accounts">
          You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these terms.
        </Section>

        <Section title="4. Subscription and Payments">
          Liquid Impact offers both free and paid subscription tiers. Paid subscriptions are billed on a recurring basis. You may cancel at any time, and cancellation will take effect at the end of the current billing period. All payments are processed securely through the App Store or Google Play.
        </Section>

        <Section title="5. Acceptable Use">
          You agree not to misuse the App, including but not limited to: attempting to reverse engineer the App, using it for commercial purposes without authorization, uploading harmful content, or circumventing usage limits.
        </Section>

        <Section title="6. AI Analysis Disclaimer">
          The health analysis provided by Liquid Impact is generated by AI and is intended for general informational purposes only. Results may not be accurate for all products. Do not rely solely on this App for health decisions. Always consult a qualified healthcare professional.
        </Section>

        <Section title="7. Privacy">
          Your use of the App is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Please review our Privacy Policy to understand our data practices.
        </Section>

        <Section title="8. Intellectual Property">
          All content, features, and functionality of the App, including but not limited to text, graphics, logos, and software, are owned by Liquid Impact and protected by intellectual property laws.
        </Section>

        <Section title="9. Limitation of Liability">
          To the fullest extent permitted by law, Liquid Impact shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App.
        </Section>

        <Section title="10. Changes to Terms">
          We reserve the right to modify these Terms at any time. We will notify you of significant changes through the App or by email. Continued use of the App after changes constitutes acceptance of the revised Terms.
        </Section>

        <Section title="11. Contact">
          If you have questions about these Terms, please contact us at: legal@liquidimpact.app
        </Section>
      </ScrollView>
    </View>
  );
}
