import type { ScanResult, LiquidCategory, GlycemicImpact, ScanStatus, Ingredient } from '../types';

export interface BaseDrinkTemplate {
  id?: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  liquidType: LiquidCategory;
  impactScore: number;
  hydrationLevel: number;
  glycemicImpact: GlycemicImpact;
  calories: number;
  sugar: number;
  caffeine: number;
  sodium: number;
  fat: number;
  protein: number;
  servingSize: number;
  servingUnit: string;
  additives: string[];
  ingredients: Ingredient[];
  alternatives: string[];
  keywords: string[];
  notes: string;
}

export const BARCODE_INDEX: Record<string, string> = {
  "5000159407280": "local_coca-cola_coca-cola_classic_global_330ml_original",
  "5000159407297": "local_coca-cola_coca-cola_zero_sugar_global_330ml_zero_sugar",
  "5000159407335": "local_coca-cola_sprite_global_330ml_original",
  "5000159407342": "local_coca-cola_fanta_orange_global_330ml_original",
  "5000159407428": "local_red_bull_gmbh_red_bull_original_global_330ml_original",
  "5000159407459": "local_monster_beverage_monster_energy_global_330ml_original",
  "5000159407397": "local_pepsico_pepsi_global_330ml_original",
  "5000159407604": "local_pepsico_gatorade_lemon_lime_global_500ml_original",
  "5000159407642": "local_danone_evian_global_500ml_original"
};

export const OCR_KEYWORD_INDEX: Record<string, { id: string; weight: number }[]> = {
  "cocacola": [
    {
      "id": "local_coca-cola_coca-cola_classic_global_330ml_original",
      "weight": 1.0
    }
  ],
  "coke": [
    {
      "id": "local_coca-cola_coca-cola_classic_global_330ml_original",
      "weight": 0.9
    }
  ],
  "sprite": [
    {
      "id": "local_coca-cola_sprite_global_330ml_original",
      "weight": 1.0
    }
  ],
  "fanta": [
    {
      "id": "local_coca-cola_fanta_orange_global_330ml_original",
      "weight": 1.0
    }
  ],
  "redbull": [
    {
      "id": "local_red_bull_gmbh_red_bull_original_global_330ml_original",
      "weight": 1.0
    }
  ],
  "pepsi": [
    {
      "id": "local_pepsico_pepsi_global_330ml_original",
      "weight": 1.0
    }
  ]
};

export const BASE_TEMPLATES: BaseDrinkTemplate[] = [
  {
    name: 'Stoney Tangawizi',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'ginger-beer',
    liquidType: 'beverage',
    impactScore: 48,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 9.5,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["stoney tangawizi", "coca-cola", "soda", "ginger-beer"],
    notes: 'Iconic Kenyan ginger beer.'
  },
  {
    name: 'Tusker Lager',
    brand: 'EABL',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 22,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["tusker lager", "eabl", "beer", "lager"],
    notes: 'Kenyan flagship beer.'
  },
  {
    name: 'Tusker Lite',
    brand: 'EABL',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 35,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["tusker lite", "eabl", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Tusker Malt',
    brand: 'EABL',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["tusker malt", "eabl", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'White Cap Lager',
    brand: 'EABL',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 24,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["white cap lager", "eabl", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'White Cap Crisp',
    brand: 'EABL',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 38,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["white cap crisp", "eabl", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Pilsner Lager',
    brand: 'EABL',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 23,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["pilsner lager", "eabl", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Guinness FES',
    brand: 'EABL',
    category: 'beer',
    subcategory: 'stout',
    liquidType: 'alcohol',
    impactScore: 28,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["guinness fes", "eabl", "beer", "stout"],
    notes: 'Global brand.'
  },
  {
    name: 'Brookside Full Cream Milk',
    brand: 'Brookside',
    category: 'milk',
    subcategory: 'dairy',
    liquidType: 'beverage',
    impactScore: 78,
    hydrationLevel: 82,
    glycemicImpact: 'low',
    calories: 64,
    sugar: 4.7,
    caffeine: 0,
    sodium: 10,
    fat: 3.3,
    protein: 3.2,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["brookside full cream milk", "brookside", "milk", "dairy"],
    notes: 'Global brand.'
  },
  {
    name: 'Brookside Low Fat Milk',
    brand: 'Brookside',
    category: 'milk',
    subcategory: 'dairy',
    liquidType: 'beverage',
    impactScore: 85,
    hydrationLevel: 82,
    glycemicImpact: 'low',
    calories: 64,
    sugar: 4.7,
    caffeine: 0,
    sodium: 10,
    fat: 3.3,
    protein: 3.2,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["brookside low fat milk", "brookside", "milk", "dairy"],
    notes: 'Global brand.'
  },
  {
    name: 'Molo Milk Fresh',
    brand: 'Molo Milk',
    category: 'milk',
    subcategory: 'dairy',
    liquidType: 'beverage',
    impactScore: 75,
    hydrationLevel: 82,
    glycemicImpact: 'low',
    calories: 64,
    sugar: 4.7,
    caffeine: 0,
    sodium: 10,
    fat: 3.3,
    protein: 3.2,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["molo milk fresh", "molo milk", "milk", "dairy"],
    notes: 'Global brand.'
  },
  {
    name: 'Tuzo Fresh Milk',
    brand: 'Brookside',
    category: 'milk',
    subcategory: 'dairy',
    liquidType: 'beverage',
    impactScore: 76,
    hydrationLevel: 82,
    glycemicImpact: 'low',
    calories: 64,
    sugar: 4.7,
    caffeine: 0,
    sodium: 10,
    fat: 3.3,
    protein: 3.2,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["tuzo fresh milk", "brookside", "milk", "dairy"],
    notes: 'Global brand.'
  },
  {
    name: 'Keringet Mineral Water',
    brand: 'Crown Beverages',
    category: 'water',
    subcategory: 'mineral',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Tap Water", "Mineral Water"],
    keywords: ["keringet mineral water", "crown beverages", "water", "mineral"],
    notes: 'Global brand.'
  },
  {
    name: 'Dasani KE',
    brand: 'Coca-Cola',
    category: 'water',
    subcategory: 'purified',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Tap Water", "Mineral Water"],
    keywords: ["dasani ke", "coca-cola", "water", "purified"],
    notes: 'Global brand.'
  },
  {
    name: 'Ketepa Pride Tea',
    brand: 'Ketepa',
    category: 'tea',
    subcategory: 'black-tea',
    liquidType: 'beverage',
    impactScore: 85,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["ketepa pride tea", "ketepa", "tea", "black-tea"],
    notes: 'Global brand.'
  },
  {
    name: 'Kericho Gold Black Tea',
    brand: 'Gold Crown',
    category: 'tea',
    subcategory: 'black-tea',
    liquidType: 'beverage',
    impactScore: 88,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["kericho gold black tea", "gold crown", "tea", "black-tea"],
    notes: 'Global brand.'
  },
  {
    name: 'Afia Mango',
    brand: 'Kevian',
    category: 'juice',
    subcategory: 'mango',
    liquidType: 'beverage',
    impactScore: 62,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Vitamin C"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["afia mango", "kevian", "juice", "mango"],
    notes: 'Global brand.'
  },
  {
    name: 'Afia Apple',
    brand: 'Kevian',
    category: 'juice',
    subcategory: 'apple',
    liquidType: 'beverage',
    impactScore: 60,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Vitamin C"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["afia apple", "kevian", "juice", "apple"],
    notes: 'Global brand.'
  },
  {
    name: 'Del Monte Pineapple',
    brand: 'Del Monte',
    category: 'juice',
    subcategory: 'pineapple',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Vitamin C"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["del monte pineapple", "del monte", "juice", "pineapple"],
    notes: 'Global brand.'
  },
  {
    name: 'Del Monte Mango',
    brand: 'Del Monte',
    category: 'juice',
    subcategory: 'mango',
    liquidType: 'beverage',
    impactScore: 52,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Vitamin C"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["del monte mango", "del monte", "juice", "mango"],
    notes: 'Global brand.'
  },
  {
    name: 'Malta Guinness',
    brand: 'Guinness',
    category: 'soda',
    subcategory: 'malt',
    liquidType: 'beverage',
    impactScore: 65,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["malta guinness", "guinness", "soda", "malt"],
    notes: 'Global brand.'
  },
  {
    name: 'Alvaro',
    brand: 'EABL',
    category: 'soda',
    subcategory: 'malt',
    liquidType: 'beverage',
    impactScore: 58,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["alvaro", "eabl", "soda", "malt"],
    notes: 'Global brand.'
  },
  {
    name: 'Coca-Cola Classic',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["coca-cola classic", "coca-cola", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Coca-Cola Zero Sugar',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["coca-cola zero sugar", "coca-cola", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Diet Coke',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 52,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["diet coke", "coca-cola", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Pepsi',
    brand: 'PepsiCo',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["pepsi", "pepsico", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Pepsi Max',
    brand: 'PepsiCo',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["pepsi max", "pepsico", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Sprite',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'lemon-lime',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["sprite", "coca-cola", "soda", "lemon-lime"],
    notes: 'Global brand.'
  },
  {
    name: 'Sprite Zero',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'lemon-lime',
    liquidType: 'beverage',
    impactScore: 58,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["sprite zero", "coca-cola", "soda", "lemon-lime"],
    notes: 'Global brand.'
  },
  {
    name: 'Fanta Orange',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'flavored',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["fanta orange", "coca-cola", "soda", "flavored"],
    notes: 'Global brand.'
  },
  {
    name: 'Dr Pepper',
    brand: 'KDP',
    category: 'soda',
    subcategory: 'cherry',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["dr pepper", "kdp", "soda", "cherry"],
    notes: 'Global brand.'
  },
  {
    name: 'Mountain Dew',
    brand: 'PepsiCo',
    category: 'soda',
    subcategory: 'citrus',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["mountain dew", "pepsico", "soda", "citrus"],
    notes: 'Global brand.'
  },
  {
    name: 'Bawls',
    brand: 'Bawls',
    category: 'soda',
    subcategory: 'guarana',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 64,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["bawls", "bawls", "soda", "guarana"],
    notes: 'Global brand.'
  },
  {
    name: 'Jarritos Tamarind',
    brand: 'Jarritos',
    category: 'soda',
    subcategory: 'mexican',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["jarritos tamarind", "jarritos", "soda", "mexican"],
    notes: 'Global brand.'
  },
  {
    name: 'Red Bull Original',
    brand: 'Red Bull',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["red bull original", "red bull", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Red Bull Sugarfree',
    brand: 'Red Bull',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 45,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["red bull sugarfree", "red bull", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Red Bull Blue Edition',
    brand: 'Red Bull',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["red bull blue edition", "red bull", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Red Bull Summer Edition',
    brand: 'Red Bull',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["red bull summer edition", "red bull", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Monster Energy',
    brand: 'Monster',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["monster energy", "monster", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Monster Ultra White',
    brand: 'Monster',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 45,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["monster ultra white", "monster", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Mango Loco',
    brand: 'Monster',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["mango loco", "monster", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Ghost Energy',
    brand: 'Ghost',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 48,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["ghost energy", "ghost", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Alani Nu',
    brand: 'Alani Nu',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 50,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["alani nu", "alani nu", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'C4 Energy',
    brand: 'C4',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 42,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["c4 energy", "c4", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Reign',
    brand: 'Monster',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 40,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["reign", "monster", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Celsius Orange',
    brand: 'Celsius',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["celsius orange", "celsius", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Bang Energy',
    brand: 'Bang',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["bang energy", "bang", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'GFuel',
    brand: 'Gamma Labs',
    category: 'energy',
    subcategory: 'powder',
    liquidType: 'beverage',
    impactScore: 45,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 160,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["gfuel", "gamma labs", "energy", "powder"],
    notes: 'Global brand.'
  },
  {
    name: 'Prime Energy',
    brand: 'Prime',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 35,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 200,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330", "Taurine"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["prime energy", "prime", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Starbucks Frappuccino Coffee',
    brand: 'Starbucks',
    category: 'coffee',
    subcategory: 'hybrid',
    liquidType: 'beverage',
    impactScore: 45,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 12,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["starbucks frappuccino coffee", "starbucks", "coffee", "hybrid"],
    notes: 'Global brand.'
  },
  {
    name: 'Starbucks Frappuccino Mocha',
    brand: 'Starbucks',
    category: 'coffee',
    subcategory: 'hybrid',
    liquidType: 'beverage',
    impactScore: 42,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 13,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["starbucks frappuccino mocha", "starbucks", "coffee", "hybrid"],
    notes: 'Global brand.'
  },
  {
    name: 'Starbucks Doubleshot',
    brand: 'Starbucks',
    category: 'coffee',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 80,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 120,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["starbucks doubleshot", "starbucks", "coffee", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Georgia Coffee',
    brand: 'Coca-Cola',
    category: 'coffee',
    subcategory: 'rtd',
    liquidType: 'beverage',
    impactScore: 80,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["georgia coffee", "coca-cola", "coffee", "rtd"],
    notes: 'Global brand.'
  },
  {
    name: 'Dunkin Iced Coffee',
    brand: 'Dunkin',
    category: 'coffee',
    subcategory: 'rtd',
    liquidType: 'beverage',
    impactScore: 80,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["dunkin iced coffee", "dunkin", "coffee", "rtd"],
    notes: 'Global brand.'
  },
  {
    name: 'La Colombe Draft Latte',
    brand: 'La Colombe',
    category: 'coffee',
    subcategory: 'rtd',
    liquidType: 'beverage',
    impactScore: 68,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["la colombe draft latte", "la colombe", "coffee", "rtd"],
    notes: 'Global brand.'
  },
  {
    name: 'Lipton Ice Tea Lemon',
    brand: 'Lipton',
    category: 'tea',
    subcategory: 'iced-tea',
    liquidType: 'beverage',
    impactScore: 80,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["lipton ice tea lemon", "lipton", "tea", "iced-tea"],
    notes: 'Global brand.'
  },
  {
    name: 'Arizona Green Tea',
    brand: 'Arizona',
    category: 'tea',
    subcategory: 'iced-tea',
    liquidType: 'beverage',
    impactScore: 80,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 9,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["arizona green tea", "arizona", "tea", "iced-tea"],
    notes: 'Global brand.'
  },
  {
    name: 'Pure Leaf Unsweetened',
    brand: 'PepsiCo',
    category: 'tea',
    subcategory: 'iced-tea',
    liquidType: 'beverage',
    impactScore: 92,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["pure leaf unsweetened", "pepsico", "tea", "iced-tea"],
    notes: 'Global brand.'
  },
  {
    name: 'Gold Peak Sweet Tea',
    brand: 'Coca-Cola',
    category: 'tea',
    subcategory: 'iced-tea',
    liquidType: 'beverage',
    impactScore: 80,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 10,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["gold peak sweet tea", "coca-cola", "tea", "iced-tea"],
    notes: 'Global brand.'
  },
  {
    name: 'Pocari Sweat',
    brand: 'Otsuka',
    category: 'sports',
    subcategory: 'electrolyte',
    liquidType: 'beverage',
    impactScore: 60,
    hydrationLevel: 90,
    glycemicImpact: 'moderate',
    calories: 25,
    sugar: 6,
    caffeine: 0,
    sodium: 45,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["pocari sweat", "otsuka", "sports", "electrolyte"],
    notes: 'Global brand.'
  },
  {
    name: 'Calpico Original',
    brand: 'Asahi',
    category: 'juice',
    subcategory: 'yogurt-drink',
    liquidType: 'beverage',
    impactScore: 50,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Vitamin C"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["calpico original", "asahi", "juice", "yogurt-drink"],
    notes: 'Global brand.'
  },
  {
    name: 'Ramune',
    brand: 'Sangaria',
    category: 'soda',
    subcategory: 'glass-marble',
    liquidType: 'beverage',
    impactScore: 35,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["E211", "E330"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["ramune", "sangaria", "soda", "glass-marble"],
    notes: 'Global brand.'
  },
  {
    name: 'Oolong Tea Drink',
    brand: 'Suntory',
    category: 'tea',
    subcategory: 'pure',
    liquidType: 'beverage',
    impactScore: 95,
    hydrationLevel: 85,
    glycemicImpact: 'low',
    calories: 2,
    sugar: 0,
    caffeine: 50,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["oolong tea drink", "suntory", "tea", "pure"],
    notes: 'Global brand.'
  },
  {
    name: 'La Croix Pamplemousse',
    brand: 'National Beverage',
    category: 'water',
    subcategory: 'sparkling',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Tap Water", "Mineral Water"],
    keywords: ["la croix pamplemousse", "national beverage", "water", "sparkling"],
    notes: 'Global brand.'
  },
  {
    name: 'Bubly Blackberry',
    brand: 'PepsiCo',
    category: 'water',
    subcategory: 'sparkling',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Tap Water", "Mineral Water"],
    keywords: ["bubly blackberry", "pepsico", "water", "sparkling"],
    notes: 'Global brand.'
  },
  {
    name: 'Spindrift Lemon',
    brand: 'Spindrift',
    category: 'water',
    subcategory: 'sparkling',
    liquidType: 'beverage',
    impactScore: 95,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Tap Water", "Mineral Water"],
    keywords: ["spindrift lemon", "spindrift", "water", "sparkling"],
    notes: 'Global brand.'
  },
  {
    name: 'Topo Chico',
    brand: 'Coca-Cola',
    category: 'water',
    subcategory: 'mineral-sparkling',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Tap Water", "Mineral Water"],
    keywords: ["topo chico", "coca-cola", "water", "mineral-sparkling"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Triple Sec',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'triple-sec',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Color"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["bols triple sec", "bols", "liqueur", "triple-sec"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Blue Curacao',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'curacao',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Color"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["bols blue curacao", "bols", "liqueur", "curacao"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Coffee',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'coffee',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ["Color"],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["bols coffee", "bols", "liqueur", "coffee"],
    notes: 'Global brand.'
  },
  {
    name: 'Smirnoff Vodka',
    brand: 'Diageo',
    category: 'spirits',
    subcategory: 'vodka',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["smirnoff vodka", "diageo", "spirits", "vodka"],
    notes: 'Global brand.'
  },
  {
    name: 'Absolut Vodka',
    brand: 'Pernod Ricard',
    category: 'spirits',
    subcategory: 'vodka',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["absolut vodka", "pernod ricard", "spirits", "vodka"],
    notes: 'Global brand.'
  },
  {
    name: 'Hennessy VS',
    brand: 'LVMH',
    category: 'spirits',
    subcategory: 'cognac',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ["Water", "Green Tea"],
    keywords: ["hennessy vs", "lvmh", "spirits", "cognac"],
    notes: 'Global brand.'
  },
];



export const EXPAND_DATABASE = (templates: BaseDrinkTemplate[]): Record<string, ScanResult> => {
  const db: Record<string, ScanResult> = {};
  const REGIONS = ['KE', 'GLOBAL'];
  const SIZES = ['330ml', '500ml', '1L'];
  const VARIANTS = ['Original', 'Zero Sugar'];

  let counter = 0;

  // First pass: add all templates by their specific ID if they have one
  templates.forEach(t => {
    if (t.id) {
       // Create a base record for the template ID
       const record: ScanResult = {
            id: t.id,
            detectedProduct: t.name,
            brand: t.brand,
            category: t.category,
            liquidType: t.liquidType,
            confidenceScore: 1.0,
            impactScore: t.impactScore,
            hydrationLevel: t.hydrationLevel,
            glycemicImpact: t.glycemicImpact,
            status: t.impactScore >= 80 ? 'optimal' : t.impactScore >= 50 ? 'stable' : t.impactScore >= 25 ? 'risky' : 'damaging',
            aiInsight: t.notes,
            viralStatement: `Checking ${t.name}.`,
            dehydrationRisk: t.sugar > 10,
            alternatives: t.alternatives,
            shortTermImpact: { energyResponse: 'Normal', bloodSugarResponse: 'Stable', bodyReaction: 'Refreshed', hydrationImpact: 'Hydrating' },
            mediumTermImpact: { energyStability: 'Stable', physicalChanges: 'None', habitRisk: 'Low', sleepQuality: 'Normal' },
            longTermImpact: { healthTrend: 'Healthy', metabolicImpact: 'Neutral', riskAccumulation: 'Low', nutritionalBalance: 'Balanced' },
            composition: {
              calories: t.calories,
              sugarGrams: t.sugar,
              caffeineMg: t.caffeine,
              sodiumMg: t.sodium,
              fatGrams: t.fat,
              proteinGrams: t.protein,
              servingSize: t.servingSize,
              servingUnit: t.servingUnit,
              artificialSweeteners: false,
              additives: t.additives,
              ingredients: t.ingredients
            },
            scannedAt: Date.now()
       };
       db[t.id] = record;
    }
  });

  // Second pass: map barcodes from BARCODE_INDEX to those template records
  Object.entries(BARCODE_INDEX).forEach(([barcode, id]) => {
    if (db[id]) {
      db[barcode] = db[id];
    }
  });

  // Third pass: expand all templates into variants
  templates.forEach(t => {
    const baseId = t.id || `local_${t.brand.replace(/\s/g, '_')}_${t.name.replace(/\s/g, '_')}`.toLowerCase();

    REGIONS.forEach(region => {
      SIZES.forEach(size => {
        VARIANTS.forEach(variant => {
          const id = `${baseId}_${region}_${size}_${variant}`.toLowerCase();
          const barcode = (100000000000 + counter).toString();

          if (db[id]) { counter++; return; } // Skip if already added

          const isZero = variant.includes('Zero') || variant.includes('Sugar') || variant.includes('Diet');
          const sugarVal = isZero ? 0 : t.sugar;
          const impactVal = isZero ? Math.min(100, t.impactScore + 20) : t.impactScore;

          const record: ScanResult = {
            id,
            detectedProduct: `${t.name} ${variant} (${size})`,
            brand: t.brand,
            category: t.category,
            liquidType: t.liquidType,
            confidenceScore: 0.95,
            impactScore: impactVal,
            hydrationLevel: t.hydrationLevel,
            glycemicImpact: isZero ? 'low' : (t.glycemicImpact as GlycemicImpact),
            status: impactVal >= 80 ? 'optimal' : impactVal >= 50 ? 'stable' : impactVal >= 25 ? 'risky' : 'damaging',
            aiInsight: `${t.notes} This ${size} ${variant} version is common in ${region}.`,
            viralStatement: `Drinking ${t.name} in ${region}? Check your score!`,
            dehydrationRisk: !isZero && t.sugar > 10,
            alternatives: t.alternatives,
            shortTermImpact: {
              energyResponse: isZero ? 'Stable energy levels.' : 'May cause a quick energy spike.',
              bloodSugarResponse: isZero ? 'Low impact on blood sugar.' : 'May cause an insulin response.',
              bodyReaction: 'Refreshed sensation.',
              hydrationImpact: t.hydrationLevel > 70 ? 'Promotes hydration.' : 'Moderate hydration effect.'
            },
            mediumTermImpact: {
              energyStability: 'Consistent if consumed in moderation.',
              physicalChanges: 'Depends on overall diet.',
              habitRisk: 'Can be habit-forming if high in sugar.',
              sleepQuality: t.caffeine > 0 ? 'May affect sleep if taken late.' : 'No impact on sleep.'
            },
            longTermImpact: {
              healthTrend: impactVal > 70 ? 'Supports a healthy lifestyle.' : 'Frequent consumption may lead to health risks.',
              metabolicImpact: isZero ? 'Metabolically neutral.' : 'High sugar may impact metabolism.',
              riskAccumulation: 'Low if occasional.',
              nutritionalBalance: 'Supplement with water.'
            },
            composition: {
              calories: isZero ? Math.round(t.calories * 0.1) : t.calories,
              sugarGrams: sugarVal,
              caffeineMg: t.caffeine,
              sodiumMg: t.sodium,
              fatGrams: t.fat,
              proteinGrams: t.protein,
              servingSize: parseInt(size) || 250,
              servingUnit: 'ml',
              artificialSweeteners: isZero,
              additives: t.additives,
              ingredients: t.ingredients
            },
            scannedAt: Date.now()
          };

          db[id] = record;
          // Only add numeric barcode if not already taken
          if (!db[barcode]) {
              db[barcode] = record;
          }
          counter++;
        });
      });
    });
  });

  return db;
};

export const DRINK_DATABASE = EXPAND_DATABASE(BASE_TEMPLATES);
