import type { ScanResult, LiquidCategory, GlycemicImpact, ScanStatus, Ingredient } from '../types';

export interface BaseDrinkTemplate {
  id?: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  liquidType: LiquidCategory;
  impactScore: number;
  hydrationLevel: number;
  glycemicImpact: GlycemicImpact;
  calories: number;
  sugar: number;
  caffeine: number;
  sodium: number;
  fat: number;
  protein: number;
  servingSize: number;
  servingUnit: string;
  additives: string[];
  ingredients: Ingredient[];
  alternatives: string[];
  keywords: string[];
  notes: string;
}

export const BARCODE_INDEX: Record<string, string> = {
  "5000159407280": "local_coca-cola_coca-cola_classic_global_330ml_original",
  "5000159407297": "local_coca-cola_coca-cola_zero_sugar_global_330ml_zero_sugar",
  "5000159407335": "local_coca-cola_sprite_global_330ml_original",
  "5000159407342": "local_coca-cola_fanta_orange_global_330ml_original",
  "5000159407428": "local_red_bull_gmbh_red_bull_original_global_330ml_original",
  "5000159407459": "local_monster_beverage_monster_energy_global_330ml_original",
  "5000159407397": "local_pepsico_pepsi_global_330ml_original",
  "5000159407604": "local_pepsico_gatorade_lemon_lime_global_500ml_original",
  "5000159407642": "local_danone_evian_global_500ml_original"
};

export const OCR_KEYWORD_INDEX: Record<string, { id: string; weight: number }[]> = {
  "cocacola": [
    {
      "id": "local_coca-cola_coca-cola_classic_global_330ml_original",
      "weight": 1.0
    }
  ],
  "coke": [
    {
      "id": "local_coca-cola_coca-cola_classic_global_330ml_original",
      "weight": 0.9
    }
  ],
  "sprite": [
    {
      "id": "local_coca-cola_sprite_global_330ml_original",
      "weight": 1.0
    }
  ],
  "fanta": [
    {
      "id": "local_coca-cola_fanta_orange_global_330ml_original",
      "weight": 1.0
    }
  ],
  "redbull": [
    {
      "id": "local_red_bull_gmbh_red_bull_original_global_330ml_original",
      "weight": 1.0
    }
  ],
  "pepsi": [
    {
      "id": "local_pepsico_pepsi_global_330ml_original",
      "weight": 1.0
    }
  ]
};

export const BASE_TEMPLATES: BaseDrinkTemplate[] = [

  {
    name: 'Coca-Cola Classic',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["coca-cola classic", "coca-cola", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Coca-Cola Zero Sugar',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["coca-cola zero sugar", "coca-cola", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Diet Coke',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["diet coke", "coca-cola", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Sprite',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'lemon-lime',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["sprite", "coca-cola", "soda", "lemon-lime"],
    notes: 'Global brand.'
  },
  {
    name: 'Sprite Zero',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'lemon-lime',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["sprite zero", "coca-cola", "soda", "lemon-lime"],
    notes: 'Global brand.'
  },
  {
    name: 'Fanta Orange',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'orange',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["fanta orange", "coca-cola", "soda", "orange"],
    notes: 'Global brand.'
  },
  {
    name: 'Fanta Grape',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'grape',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["fanta grape", "coca-cola", "soda", "grape"],
    notes: 'Global brand.'
  },
  {
    name: 'Fanta Strawberry',
    brand: 'Coca-Cola',
    category: 'soda',
    subcategory: 'strawberry',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["fanta strawberry", "coca-cola", "soda", "strawberry"],
    notes: 'Global brand.'
  },
  {
    name: 'Pepsi',
    brand: 'PepsiCo',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["pepsi", "pepsico", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Pepsi Zero Sugar',
    brand: 'PepsiCo',
    category: 'soda',
    subcategory: 'cola',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["pepsi zero sugar", "pepsico", "soda", "cola"],
    notes: 'Global brand.'
  },
  {
    name: 'Mountain Dew',
    brand: 'PepsiCo',
    category: 'soda',
    subcategory: 'citrus',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["mountain dew", "pepsico", "soda", "citrus"],
    notes: 'Global brand.'
  },
  {
    name: 'Baja Blast',
    brand: 'PepsiCo',
    category: 'soda',
    subcategory: 'tropical-lime',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["baja blast", "pepsico", "soda", "tropical-lime"],
    notes: 'Global brand.'
  },
  {
    name: '7UP',
    brand: 'Keurig Dr Pepper',
    category: 'soda',
    subcategory: 'lemon-lime',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["7up", "keurig dr pepper", "soda", "lemon-lime"],
    notes: 'Global brand.'
  },
  {
    name: 'Dr Pepper',
    brand: 'Keurig Dr Pepper',
    category: 'soda',
    subcategory: 'spiced-cherry',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["dr pepper", "keurig dr pepper", "soda", "spiced-cherry"],
    notes: 'Global brand.'
  },
  {
    name: 'Canada Dry',
    brand: 'Keurig Dr Pepper',
    category: 'soda',
    subcategory: 'ginger-ale',
    liquidType: 'beverage',
    impactScore: 30,
    hydrationLevel: 30,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["canada dry", "keurig dr pepper", "soda", "ginger-ale"],
    notes: 'Global brand.'
  },
  {
    name: 'Red Bull Original',
    brand: 'Red Bull GmbH',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["red bull original", "red bull gmbh", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Red Bull Sugarfree',
    brand: 'Red Bull GmbH',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["red bull sugarfree", "red bull gmbh", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Monster Energy',
    brand: 'Monster Beverage',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["monster energy", "monster beverage", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Monster Ultra White',
    brand: 'Monster Beverage',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["monster ultra white", "monster beverage", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Mango Loco',
    brand: 'Monster Beverage',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["mango loco", "monster beverage", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Celsius Orange',
    brand: 'Celsius',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["celsius orange", "celsius", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Rockstar Original',
    brand: 'Rockstar',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["rockstar original", "rockstar", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Bang Energy Star Blast',
    brand: 'Bang',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bang energy star blast", "bang", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Prime Energy',
    brand: 'Prime',
    category: 'energy',
    subcategory: 'energy',
    liquidType: 'beverage',
    impactScore: 25,
    hydrationLevel: 25,
    glycemicImpact: 'high',
    calories: 45,
    sugar: 11,
    caffeine: 32,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330', 'Taurine'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["prime energy", "prime", "energy", "energy"],
    notes: 'Global brand.'
  },
  {
    name: 'Dasani',
    brand: 'Coca-Cola',
    category: 'water',
    subcategory: 'purified',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["dasani", "coca-cola", "water", "purified"],
    notes: 'Global brand.'
  },
  {
    name: 'Smartwater',
    brand: 'Coca-Cola',
    category: 'water',
    subcategory: 'distilled',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["smartwater", "coca-cola", "water", "distilled"],
    notes: 'Global brand.'
  },
  {
    name: 'Aquafina',
    brand: 'PepsiCo',
    category: 'water',
    subcategory: 'purified',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["aquafina", "pepsico", "water", "purified"],
    notes: 'Global brand.'
  },
  {
    name: 'Evian',
    brand: 'Danone',
    category: 'water',
    subcategory: 'spring',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["evian", "danone", "water", "spring"],
    notes: 'Global brand.'
  },
  {
    name: 'Fiji Water',
    brand: 'Fiji',
    category: 'water',
    subcategory: 'artesian',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["fiji water", "fiji", "water", "artesian"],
    notes: 'Global brand.'
  },
  {
    name: 'Voss',
    brand: 'Voss',
    category: 'water',
    subcategory: 'artesian',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["voss", "voss", "water", "artesian"],
    notes: 'Global brand.'
  },
  {
    name: 'Liquid Death',
    brand: 'Liquid Death',
    category: 'water',
    subcategory: 'mountain',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["liquid death", "liquid death", "water", "mountain"],
    notes: 'Global brand.'
  },
  {
    name: 'Perrier',
    brand: 'Nestle',
    category: 'water',
    subcategory: 'sparkling',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["perrier", "nestle", "water", "sparkling"],
    notes: 'Global brand.'
  },
  {
    name: 'San Pellegrino',
    brand: 'Nestle',
    category: 'water',
    subcategory: 'sparkling',
    liquidType: 'beverage',
    impactScore: 98,
    hydrationLevel: 100,
    glycemicImpact: 'low',
    calories: 0,
    sugar: 0,
    caffeine: 0,
    sodium: 2,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Tap Water', 'Mineral Water'],
    keywords: ["san pellegrino", "nestle", "water", "sparkling"],
    notes: 'Global brand.'
  },
  {
    name: 'Tropicana Pure Premium',
    brand: 'Tropicana',
    category: 'juice',
    subcategory: 'orange',
    liquidType: 'beverage',
    impactScore: 65,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Vitamin C'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["tropicana pure premium", "tropicana", "juice", "orange"],
    notes: 'Global brand.'
  },
  {
    name: 'Minute Maid Orange Juice',
    brand: 'Coca-Cola',
    category: 'juice',
    subcategory: 'orange',
    liquidType: 'beverage',
    impactScore: 65,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Vitamin C'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["minute maid orange juice", "coca-cola", "juice", "orange"],
    notes: 'Global brand.'
  },
  {
    name: 'Simply Orange',
    brand: 'Simply Beverages',
    category: 'juice',
    subcategory: 'orange',
    liquidType: 'beverage',
    impactScore: 65,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Vitamin C'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["simply orange", "simply beverages", "juice", "orange"],
    notes: 'Global brand.'
  },
  {
    name: 'Ocean Spray Cranberry',
    brand: 'Ocean Spray',
    category: 'juice',
    subcategory: 'cranberry',
    liquidType: 'beverage',
    impactScore: 65,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Vitamin C'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["ocean spray cranberry", "ocean spray", "juice", "cranberry"],
    notes: 'Global brand.'
  },
  {
    name: 'V8 Original',
    brand: 'Campbell',
    category: 'juice',
    subcategory: 'vegetable',
    liquidType: 'beverage',
    impactScore: 65,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Vitamin C'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["v8 original", "campbell", "juice", "vegetable"],
    notes: 'Global brand.'
  },
  {
    name: 'Naked Juice Green Machine',
    brand: 'Naked',
    category: 'juice',
    subcategory: 'smoothie',
    liquidType: 'beverage',
    impactScore: 65,
    hydrationLevel: 60,
    glycemicImpact: 'moderate',
    calories: 45,
    sugar: 10,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Vitamin C'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["naked juice green machine", "naked", "juice", "smoothie"],
    notes: 'Global brand.'
  },
  {
    name: 'Gatorade Lemon Lime',
    brand: 'PepsiCo',
    category: 'sports',
    subcategory: 'electrolyte',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 90,
    glycemicImpact: 'moderate',
    calories: 25,
    sugar: 6,
    caffeine: 0,
    sodium: 45,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["gatorade lemon lime", "pepsico", "sports", "electrolyte"],
    notes: 'Global brand.'
  },
  {
    name: 'Gatorade Orange',
    brand: 'PepsiCo',
    category: 'sports',
    subcategory: 'electrolyte',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 90,
    glycemicImpact: 'moderate',
    calories: 25,
    sugar: 6,
    caffeine: 0,
    sodium: 45,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["gatorade orange", "pepsico", "sports", "electrolyte"],
    notes: 'Global brand.'
  },
  {
    name: 'Powerade Mountain Berry',
    brand: 'Coca-Cola',
    category: 'sports',
    subcategory: 'electrolyte',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 90,
    glycemicImpact: 'moderate',
    calories: 25,
    sugar: 6,
    caffeine: 0,
    sodium: 45,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["powerade mountain berry", "coca-cola", "sports", "electrolyte"],
    notes: 'Global brand.'
  },
  {
    name: 'BodyArmor Fruit Punch',
    brand: 'Coca-Cola',
    category: 'sports',
    subcategory: 'electrolyte',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 90,
    glycemicImpact: 'moderate',
    calories: 25,
    sugar: 6,
    caffeine: 0,
    sodium: 45,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bodyarmor fruit punch", "coca-cola", "sports", "electrolyte"],
    notes: 'Global brand.'
  },
  {
    name: 'Prime Hydration Blue Raspberry',
    brand: 'Prime',
    category: 'sports',
    subcategory: 'electrolyte',
    liquidType: 'beverage',
    impactScore: 55,
    hydrationLevel: 90,
    glycemicImpact: 'moderate',
    calories: 25,
    sugar: 6,
    caffeine: 0,
    sodium: 45,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['E211', 'E330'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["prime hydration blue raspberry", "prime", "sports", "electrolyte"],
    notes: 'Global brand.'
  },
  {
    name: 'Budweiser',
    brand: 'AB InBev',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 22,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["budweiser", "ab inbev", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Bud Light',
    brand: 'AB InBev',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 22,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bud light", "ab inbev", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Corona Extra',
    brand: 'AB InBev',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 22,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["corona extra", "ab inbev", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Heineken',
    brand: 'Heineken',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 22,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["heineken", "heineken", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Guinness Draught',
    brand: 'Diageo',
    category: 'beer',
    subcategory: 'stout',
    liquidType: 'alcohol',
    impactScore: 22,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["guinness draught", "diageo", "beer", "stout"],
    notes: 'Global brand.'
  },
  {
    name: 'Stella Artois',
    brand: 'AB InBev',
    category: 'beer',
    subcategory: 'lager',
    liquidType: 'alcohol',
    impactScore: 22,
    hydrationLevel: 25,
    glycemicImpact: 'moderate',
    calories: 42,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["stella artois", "ab inbev", "beer", "lager"],
    notes: 'Global brand.'
  },
  {
    name: 'Smirnoff No. 21',
    brand: 'Diageo',
    category: 'spirits',
    subcategory: 'vodka',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["smirnoff no. 21", "diageo", "spirits", "vodka"],
    notes: 'Global brand.'
  },
  {
    name: 'Absolut Vodka',
    brand: 'Pernod Ricard',
    category: 'spirits',
    subcategory: 'vodka',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["absolut vodka", "pernod ricard", "spirits", "vodka"],
    notes: 'Global brand.'
  },
  {
    name: 'Titos Handmade Vodka',
    brand: 'Titos',
    category: 'spirits',
    subcategory: 'vodka',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["titos handmade vodka", "titos", "spirits", "vodka"],
    notes: 'Global brand.'
  },
  {
    name: 'Jack Daniels Old No. 7',
    brand: 'Brown-Forman',
    category: 'spirits',
    subcategory: 'whiskey',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["jack daniels old no. 7", "brown-forman", "spirits", "whiskey"],
    notes: 'Global brand.'
  },
  {
    name: 'Jameson Irish Whiskey',
    brand: 'Pernod Ricard',
    category: 'spirits',
    subcategory: 'whiskey',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["jameson irish whiskey", "pernod ricard", "spirits", "whiskey"],
    notes: 'Global brand.'
  },
  {
    name: 'Johnnie Walker Black Label',
    brand: 'Diageo',
    category: 'spirits',
    subcategory: 'scotch',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["johnnie walker black label", "diageo", "spirits", "scotch"],
    notes: 'Global brand.'
  },
  {
    name: 'Bacardi Superior',
    brand: 'Bacardi',
    category: 'spirits',
    subcategory: 'rum',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bacardi superior", "bacardi", "spirits", "rum"],
    notes: 'Global brand.'
  },
  {
    name: 'Captain Morgan Spiced Rum',
    brand: 'Diageo',
    category: 'spirits',
    subcategory: 'rum',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["captain morgan spiced rum", "diageo", "spirits", "rum"],
    notes: 'Global brand.'
  },
  {
    name: 'Patron Silver',
    brand: 'Bacardi',
    category: 'spirits',
    subcategory: 'tequila',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["patron silver", "bacardi", "spirits", "tequila"],
    notes: 'Global brand.'
  },
  {
    name: 'Don Julio Blanco',
    brand: 'Diageo',
    category: 'spirits',
    subcategory: 'tequila',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["don julio blanco", "diageo", "spirits", "tequila"],
    notes: 'Global brand.'
  },
  {
    name: 'Bombay Sapphire',
    brand: 'Bacardi',
    category: 'spirits',
    subcategory: 'gin',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bombay sapphire", "bacardi", "spirits", "gin"],
    notes: 'Global brand.'
  },
  {
    name: 'Tanqueray London Dry',
    brand: 'Diageo',
    category: 'spirits',
    subcategory: 'gin',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["tanqueray london dry", "diageo", "spirits", "gin"],
    notes: 'Global brand.'
  },
  {
    name: 'Hennessy VS',
    brand: 'LVMH',
    category: 'spirits',
    subcategory: 'cognac',
    liquidType: 'alcohol',
    impactScore: 15,
    hydrationLevel: 15,
    glycemicImpact: 'moderate',
    calories: 65,
    sugar: 0,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: [],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["hennessy vs", "lvmh", "spirits", "cognac"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Triple Sec',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'triple-sec',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bols triple sec", "bols", "liqueur", "triple-sec"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Blue Curacao',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'curacao',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bols blue curacao", "bols", "liqueur", "curacao"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Amaretto',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'nut',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bols amaretto", "bols", "liqueur", "nut"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Coffee',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'coffee',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bols coffee", "bols", "liqueur", "coffee"],
    notes: 'Global brand.'
  },
  {
    name: 'Bols Peach',
    brand: 'Bols',
    category: 'liqueur',
    subcategory: 'fruit',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["bols peach", "bols", "liqueur", "fruit"],
    notes: 'Global brand.'
  },
  {
    name: 'Baileys Irish Cream',
    brand: 'Diageo',
    category: 'liqueur',
    subcategory: 'cream',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["baileys irish cream", "diageo", "liqueur", "cream"],
    notes: 'Global brand.'
  },
  {
    name: 'Kahlua',
    brand: 'Pernod Ricard',
    category: 'liqueur',
    subcategory: 'coffee',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["kahlua", "pernod ricard", "liqueur", "coffee"],
    notes: 'Global brand.'
  },
  {
    name: 'Jagermeister',
    brand: 'Mast-Jagermeister',
    category: 'liqueur',
    subcategory: 'herbal',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["jagermeister", "mast-jagermeister", "liqueur", "herbal"],
    notes: 'Global brand.'
  },
  {
    name: 'Aperol',
    brand: 'Campari Group',
    category: 'liqueur',
    subcategory: 'herbal',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["aperol", "campari group", "liqueur", "herbal"],
    notes: 'Global brand.'
  },
  {
    name: 'Campari',
    brand: 'Campari Group',
    category: 'liqueur',
    subcategory: 'herbal',
    liquidType: 'alcohol',
    impactScore: 10,
    hydrationLevel: 10,
    glycemicImpact: 'moderate',
    calories: 100,
    sugar: 20,
    caffeine: 0,
    sodium: 10,
    fat: 0,
    protein: 0,
    servingSize: 100,
    servingUnit: 'ml',
    additives: ['Color'],
    ingredients: [{ name: 'Water', function: 'Base', healthRole: 'neutral', riskLevel: 'low' }],
    alternatives: ['Water', 'Green Tea'],
    keywords: ["campari", "campari group", "liqueur", "herbal"],
    notes: 'Global brand.'
  },

];

export const EXPAND_DATABASE = (templates: BaseDrinkTemplate[]): Record<string, ScanResult> => {
  const db: Record<string, ScanResult> = {};
  const REGIONS = ['KE', 'GLOBAL'];
  const SIZES = ['330ml', '500ml', '1L'];
  const VARIANTS = ['Original', 'Zero Sugar'];

  let counter = 0;

  // First pass: add all templates by their specific ID if they have one
  templates.forEach(t => {
    if (t.id) {
       // Create a base record for the template ID
       const record: ScanResult = {
            id: t.id,
            detectedProduct: t.name,
            brand: t.brand,
            category: t.category,
            liquidType: t.liquidType,
            confidenceScore: 1.0,
            impactScore: t.impactScore,
            hydrationLevel: t.hydrationLevel,
            glycemicImpact: t.glycemicImpact,
            status: t.impactScore >= 80 ? 'optimal' : t.impactScore >= 50 ? 'stable' : t.impactScore >= 25 ? 'risky' : 'damaging',
            aiInsight: t.notes,
            viralStatement: `Checking ${t.name}.`,
            dehydrationRisk: t.sugar > 10,
            alternatives: t.alternatives,
            shortTermImpact: { energyResponse: 'Normal', bloodSugarResponse: 'Stable', bodyReaction: 'Refreshed', hydrationImpact: 'Hydrating' },
            mediumTermImpact: { energyStability: 'Stable', physicalChanges: 'None', habitRisk: 'Low', sleepQuality: 'Normal' },
            longTermImpact: { healthTrend: 'Healthy', metabolicImpact: 'Neutral', riskAccumulation: 'Low', nutritionalBalance: 'Balanced' },
            composition: {
              calories: t.calories,
              sugarGrams: t.sugar,
              caffeineMg: t.caffeine,
              sodiumMg: t.sodium,
              fatGrams: t.fat,
              proteinGrams: t.protein,
              servingSize: t.servingSize,
              servingUnit: t.servingUnit,
              artificialSweeteners: false,
              additives: t.additives,
              ingredients: t.ingredients
            },
            scannedAt: Date.now()
       };
       db[t.id] = record;
    }
  });

  // Second pass: map barcodes from BARCODE_INDEX to those template records
  Object.entries(BARCODE_INDEX).forEach(([barcode, id]) => {
    if (db[id]) {
      db[barcode] = db[id];
    }
  });

  // Third pass: expand all templates into variants
  templates.forEach(t => {
    const baseId = t.id || `local_${t.brand.replace(/\s/g, '_')}_${t.name.replace(/\s/g, '_')}`.toLowerCase();

    REGIONS.forEach(region => {
      SIZES.forEach(size => {
        VARIANTS.forEach(variant => {
          const id = `${baseId}_${region}_${size}_${variant}`.toLowerCase();
          const barcode = (100000000000 + counter).toString();

          if (db[id]) { counter++; return; } // Skip if already added

          const isZero = variant.includes('Zero') || variant.includes('Sugar') || variant.includes('Diet');
          const sugarVal = isZero ? 0 : t.sugar;
          const impactVal = isZero ? Math.min(100, t.impactScore + 20) : t.impactScore;

          const record: ScanResult = {
            id,
            detectedProduct: `${t.name} ${variant} (${size})`,
            brand: t.brand,
            category: t.category,
            liquidType: t.liquidType,
            confidenceScore: 0.95,
            impactScore: impactVal,
            hydrationLevel: t.hydrationLevel,
            glycemicImpact: isZero ? 'low' : (t.glycemicImpact as GlycemicImpact),
            status: impactVal >= 80 ? 'optimal' : impactVal >= 50 ? 'stable' : impactVal >= 25 ? 'risky' : 'damaging',
            aiInsight: `${t.notes} This ${size} ${variant} version is common in ${region}.`,
            viralStatement: `Drinking ${t.name} in ${region}? Check your score!`,
            dehydrationRisk: !isZero && t.sugar > 10,
            alternatives: t.alternatives,
            shortTermImpact: {
              energyResponse: isZero ? 'Stable energy levels.' : 'May cause a quick energy spike.',
              bloodSugarResponse: isZero ? 'Low impact on blood sugar.' : 'May cause an insulin response.',
              bodyReaction: 'Refreshed sensation.',
              hydrationImpact: t.hydrationLevel > 70 ? 'Promotes hydration.' : 'Moderate hydration effect.'
            },
            mediumTermImpact: {
              energyStability: 'Consistent if consumed in moderation.',
              physicalChanges: 'Depends on overall diet.',
              habitRisk: 'Can be habit-forming if high in sugar.',
              sleepQuality: t.caffeine > 0 ? 'May affect sleep if taken late.' : 'No impact on sleep.'
            },
            longTermImpact: {
              healthTrend: impactVal > 70 ? 'Supports a healthy lifestyle.' : 'Frequent consumption may lead to health risks.',
              metabolicImpact: isZero ? 'Metabolically neutral.' : 'High sugar may impact metabolism.',
              riskAccumulation: 'Low if occasional.',
              nutritionalBalance: 'Supplement with water.'
            },
            composition: {
              calories: isZero ? Math.round(t.calories * 0.1) : t.calories,
              sugarGrams: sugarVal,
              caffeineMg: t.caffeine,
              sodiumMg: t.sodium,
              fatGrams: t.fat,
              proteinGrams: t.protein,
              servingSize: parseInt(size) || 250,
              servingUnit: 'ml',
              artificialSweeteners: isZero,
              additives: t.additives,
              ingredients: t.ingredients
            },
            scannedAt: Date.now()
          };

          db[id] = record;
          // Only add numeric barcode if not already taken
          if (!db[barcode]) {
              db[barcode] = record;
          }
          counter++;
        });
      });
    });
  });

  return db;
};

export const DRINK_DATABASE = EXPAND_DATABASE(BASE_TEMPLATES);
